### ISSUE TITLE
[Question] How to use execution providers?

### ISSUE THREAD

**Issue by CaptainDario** [gtbluesky/onnxruntime_flutter#10]
The ONNX runtime provides a [long list of execution providers](https://onnxruntime.ai/docs/execution-providers/). Now I am wondering if this package intents to support all / any of those?

**Comment by CaptainDario** [comment]
@gtbluesky so you are not planning on adding those?

**Comment by sun-jiao** [comment]
@gtbluesky Hi, how to choose tags?
